NHSDigital/nhs-app-api

Makefile, azure/azure-pr-pipeline.yml, ecs-proxies-containers.yml, ecs-proxies-deploy.yml, proxies/sandbox/apiproxy/targets/sandbox.xml, sandbox/Dockerfile
=> APM-000 Add sandbox to ecs

proxies/live/apiproxy/targets/nhsa-target.xml
Temporarily disable quota checks
----
=> APM-1162 Remove all pre-flow quota checks for now

.github/workflows/pr-lint.yaml
=> NHSO-10764: Add NHSO ticket namespace

proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/targets/nhsa-target.xml
=> NHSO-11329: Enable Apigee api key in header

proxies/live/apiproxy/policies/AssignMessage.AddUpstreamApiKeyHeader.xml, proxies/live/apiproxy/policies/AssignMessage.RemoveApiKeyHeader.xml, proxies/live/apiproxy/policies/KeyValueMap.GetUpstreamApiKey.xml, proxies/live/apiproxy/targets/nhsa-target.xml
=> NHSO-11328: Add upstream api key

azure/azure-release-pipeline.yml
=> NHSO-11357: Make spec visible on int

azure/azure-release-pipeline.yml
=> NHSO-10764: Temporarily remove dependency on qa when deploying to int

proxies/live/apiproxy/proxies/default.xml
=> NHSO-11418: Correlation Id header validation on GET endpoint

specification/nhs-app.yaml
=> Nhso 10231 spec

specification/nhs-app.yaml
=> NHSO-10231: Spec update

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml, proxies/live/apiproxy/proxies/default.xml
=> NHSO-11529: Add splunk logging

specification/nhs-app.yaml
=> NHSO-10231: Fix paths in documentation

specification/components/examples/requests/communication/appMessage.json, specification/components/schemas/communication.yaml, specification/nhs-app.yaml
=> NHSO-10231: Change spec onboarding details.

.github/workflows/continuous-integration.yml, .github/workflows/pr-lint.yaml, azure/azure-release-pipeline.yml
Adding dev environment, removing sandbox environments
=> NHSO-11357: Add Dev environment, remove Sandbox environments

.github/workflows/pr-lint.yaml
=> APM-1623 Fix jira link too

specification/components/examples/requests/communication/appMessage.json, specification/components/examples/requests/communication/appMessageAndPushNotification.json, specification/components/examples/requests/communication/pushNotification.json, specification/components/schemas/communication.yaml, specification/nhs-app.yaml
* :sparkles: Documentation for push notifications
=> NHSO-10803: Push Notification documentation

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml
Remove need to enter a callback URI when signing up the NHS App API through the developer portal.
=> NHSO-11890: Remove need for callback URI when signing up to API in portal

specification/nhs-app.yaml
Documentation changes:
* We now support sending push notifications.
* Casing correction - NHS Numbers
* Casing correction - communication
=> NHSO-12557: Documentation updates

CHANGELOG.md, README.md
Documentation changes - removed changelog, updated readme.
=> NHSO-12700: Minor changes to documentation

proxies/live/apiproxy/policies/JavaScript.SetStatusResponse.xml, proxies/live/apiproxy/policies/KeyValueMapOperations.GetSharedSecureVariables.xml, proxies/live/apiproxy/policies/RaiseFault.401Unauthorized.xml, proxies/live/apiproxy/policies/ServiceCallout.CallHealthCheckEndpoint.xml, proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/resources/jsc/SetStatusResponse.js
=> NHSO-12769: Add _status endpoint

proxies/live/apiproxy/policies/Quota.xml, proxies/live/apiproxy/policies/SpikeArrest.xml
Update Quota and SpikeArrest policies as per APM-1162
=> NHSO-12801: Update Quota and SpikeArrest policies as per APM-1162

azure/azure-release-pipeline.yml
Modified release pipeline to enable monitoring for all none-PR environments.
Do not merge this until NHSO-12768 (_ping endpoint) and NHSO-12769 (_status endpoint) have been merged and deployed to all these environments.
=> NHSO-12775: Enable monitoring on release environments

azure/azure-release-pipeline.yml
* :robot: Enabling monitoring of _status endpoint
=> NHSO-12775: Enable monitoring of _status endpoint

proxies/live/apiproxy/policies/AssignMessage.SetHeader.NhsdCorrelationId.xml, proxies/live/apiproxy/policies/AssignMessage.SetHeader.NhsdSupplierAppId.xml, proxies/live/apiproxy/targets/nhsa-target.xml
Fix bug with derived header being concatenated to existing header content, should a consumer pass an existing header of the same name.
=> NHSO-12767: Headers bug

specification/components/schemas/communication.yaml
=> Nhso-11714: markdown documentation

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionBase.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsLegacyTests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/FhirR4IdentifierSystem.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests.csproj
* :sparkles: In-App message FHIR R4 endpoint - integration tests
=> NHSO-11326: Comms Hub FHIR Support - in-app message endpoint

azure/azure-release-pipeline.yml
Enable prod deployments of NHS App API
=> NHSO-12822: Enable prod deployments

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
=>  NHSO-12650: FHIR - support for push notifications

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
=> NHSO-12650: Test refactoring

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
=> NHSO-12651: FHIR validation integration tests

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
=> NHSO-13027: Derive sender name from FHIR sender property, not requester

postman/NHS App - dev (NHS Login sandpit).postman_environment.json, postman/NHS App - int (NHS Login AOS).postman_environment.json, postman/NHS App - internal-dev.postman_environment.json, postman/NHS App - internal-qa.postman_environment.json, postman/NHS App - production.postman_environment.json, postman/NHS App.postman_collection.json
=> NHSO-12920: Add postman collection and environments

specification/nhs-app.yaml
Documentation change - transition from alpha to private beta
=> NHSO-0000: Documentation change - API status

azure/azure-pr-pipeline.yml
Modify Azure build pipeline to remove deployment to sandbox, as we are not currently making use of this environment.
=> NHSO-0000: Remove deployment to sandbox

specification/components/schemas/communication.yaml
=> NHSO-0000: Documentation update - we support push notifications

specification/components/examples/responses/communication/401invalidAccessToken.json, specification/components/schemas/ErrorCode.yaml, specification/components/schemas/OperationOutcome.yaml, specification/nhs-app.yaml
Documentation changes for signed JWT authentication
=> NHSO-13097: Docmentation changes for jwt auth

azure/azure-pr-pipeline.yml, azure/templates/run-integration-tests.yml, proxies/live/apiproxy/policies/AssignMessage.SetHeader.XApiKey.xml, proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml, proxies/live/apiproxy/targets/nhsa-target.xml, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionBase.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsLegacyTests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests.csproj, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/AccessTokenGenerationException.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/AccessTokenService/AccessTokenCacheService.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/AccessTokenService/AccessTokenDto.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/AccessTokenService/IAccessTokenCacheService.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/AccessTokenService/JwtResponse.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/NhsAppApiApiKeyWrapperClient.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/NhsAppApiJwtWrapperClient.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/TestConfiguration.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/test.runsettings
* :exclamation: Switch from api key authentication to signed JWT authentication
=> NHSO-11327: Signed JWT Authentication

specification/components/schemas/communication-in-app-push-notifications.yaml, specification/components/schemas/communication-in-app.yaml, specification/components/schemas/communication.yaml, specification/nhs-app.yaml
=> NHSO-13078: Increase max in-app message body length to 5000 characters

postman/NHS App - dev (NHS Login sandpit).postman_environment.json, postman/NHS App - int (NHS Login AOS).postman_environment.json, postman/NHS App - internal-dev.postman_environment.json, postman/NHS App - internal-qa.postman_environment.json, postman/NHS App - production.postman_environment.json, postman/NHS App.postman_collection.json, postman/README.MD
=> NHSO-11327: Setup postman collections to support jwt authentication

proxies/live/apiproxy/proxies/default.xml, proxies/live/apiproxy/targets/nhsa-target.xml
=> NHSO-13083: Mirror X-Correlation-Id on fault responses

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/FhirR4IdentifierSystem.cs
=> NHSO-13248: Return FHIR resource in success response body

postman/NHS App - dev (NHS Login sandpit).postman_environment.json, postman/NHS App - int (NHS Login AOS).postman_environment.json, postman/NHS App - internal-dev.postman_environment.json, postman/NHS App - internal-qa.postman_environment.json, postman/NHS App - production.postman_environment.json, postman/NHS App.postman_collection.json
=> NHSO-13294: postman collection changes

proxies/live/apiproxy/targets/nhsa-target.xml, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionBase.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Extensions/HttpResponseHeadersExtensions.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Services/NhsAppApiJwtWrapperClient.cs
=> NHSO-13250: Test correlation ID mirrored back to consumer

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
=> NHSO-13255: Catch-all error integration test

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
=> NHSO-0000: Test assertion improvement

specification/components/schemas/communication-in-app-push-notifications.yaml, specification/components/schemas/communication-in-app.yaml, specification/components/schemas/communication-push-notifications.yaml, specification/components/schemas/communication.yaml, specification/nhs-app.yaml
=> Ms nhso 960 adz fix nhs number

postman/NHS App.postman_collection.json
=> NHSO-10867: Add event report endpoint to postman collection

proxies/live/apiproxy/targets/nhsa-target.xml
A band-aid to allow GNCR to temporarily use the legacy Communication endpoint with a capital leading C in the path.
=> NHSO-0000: Allow variant casing of legacy communication endpoint

specification/components/examples/responses/communication/401invalidAccessToken.json
=> NHSO-13807: Added diagnostics to example response

README.md
=> NHSO-14952: Fix digital developer hub url

specification/components/schemas/Markdown.yaml, specification/components/schemas/communication-in-app-push-notifications.yaml, specification/components/schemas/communication-in-app.yaml, specification/components/schemas/communication.yaml
…ne breaks in markdown messages
=> NHSO-14892: Update documentation to detail support for line breaks

specification/nhs-app.yaml
"Who can use this API" heading should be a statement, not a question.
=> NHSO-0000: Documentation tweak

manifest_template.yml
* :robot: Add external dev environment to manifest template
=> NHSO-15526: Add dev environment to manifest template

postman/NHS App.postman_collection.json
=> NHSO-15624: Postman collection update

proxies/live/apiproxy/policies/RaiseFault.404NotFound.xml, proxies/live/apiproxy/proxies/default.xml, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/EventReportsHttpFunctionsTests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Models/EventReportCreateRequest.cs
=> NHSO-13473: Return 404 to apigee from test endpoints

specification/components/schemas/OperationOutcome.yaml
=> NHSO-15972: Mapped to ADZ-894 - Remove readOnly label from response schema

proxies/live/apiproxy/policies/AssignMessage.OAuthPolicyErrorResponse.xml, proxies/live/apiproxy/policies/ExtractVariables.OAuthErrorFaultString.xml, proxies/live/apiproxy/policies/JavaScript.OAuthErrorCode.xml, proxies/live/apiproxy/resources/jsc/set-oauth-error-code.js, proxies/live/apiproxy/targets/nhsa-target.xml, specification/components/examples/responses/communication/401ExpiredAccessToken.json, specification/nhs-app.yaml
=> NHSO-15830: Differentiate error responses

postman/NHS App.postman_collection.json
* Postman collection update to add additional querystring parameter
=> NHSO-15784: Postman collection update

specification/nhs-app.yaml
* Updating API specification to document the 10pm-6am push notification Quiet Time that was implemented in NHSO-15005.
=> NHSO-15384: Quiet time documentation (NHSO-15005)

specification/nhs-app.yaml
* Updating API specification to document the configurable push notification content (NHSO-12676).
=> NHSO-15838: Configurable push notification content documentation (NHSO-12676)

specification/nhs-app.yaml
* Mention postman collection and C# integration tests in specification
=> NHSO-15833: Mention postman collection and c# integration tests in docs

proxies/live/apiproxy/policies/JavaScript.Header.Rewrite.Link.xml, proxies/live/apiproxy/resources/jsc/rewrite-link-header.js, proxies/live/apiproxy/targets/nhsa-target.xml
* Add apigee policy to rewrite domains in link headers
=> NHSO-15782: link-header-domain

postman/NHS App.postman_collection.json
* Add postman collection endpoint for patient report
=> NHSO-16198: Postman collection endpoint for patient report

specification/components/examples/responses/communication/403permissionsMissingForAppMessage.json, specification/components/examples/responses/communication/403permissionsMissingForEventReport.json, specification/components/examples/responses/communication/403permissionsMissingForPatientReport.json, specification/components/examples/responses/communication/403permissionsMissingForPushNotification.json, specification/nhs-app.yaml
* NHSO-16314: Update specification examples for 403 forbidden errors 
=> NHSO-16314: Update specification examples for 403 forbidden errors

proxies/live/apiproxy/policies/AssignMessage.QuotaLimitsBreachedErrorResponse.xml, proxies/live/apiproxy/targets/nhsa-target.xml
* Return custom error when spike/quota limits are hit
=> NHSO-16054: Return custom error when spike/quota limits are hit

specification/components/examples/responses/communication/429throttled.json, specification/components/schemas/OperationOutcome.yaml, specification/nhs-app.yaml
* NHSO-16578: Specification changes relating to custom 429 error (see PR150 - https://github.com/NHSDigital/nhs-app-api/pull/150)
=> NHSO-16578: Specification changes for custom 429 error

specification/nhs-app.yaml
* Documentation change - clarify NHS Login integration environment name
=> NHSO-0000: Clarify NHS Login integration environment name

proxies/live/apiproxy/proxies/default.xml, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/EventReportsHttpFunctionsTests.cs
* NHSO-16754: Return 404 from internal/runtime endpoints
=> NHSO-16754: Return 404 from internal/runtime endpoints

specification/nhs-app.yaml
* Documentation change - explain that App IDs need to be granted permissions by NHS App onboarding team.
=> NHSO-0000: Documentation update

SECURITY.md
=> NHSO-0000: Add security.md

postman/README.MD
* corrected spelling of "generated"
=> NHSO-0000: Fix typo in readme file

specification/nhs-app.yaml
=> NHSO-18296: Remove disclaimer from patient report and event report spec

azure/azure-release-pipeline.yml, manifest_template.yml
* :robot: Added reference (ref) environment in manifest_template.yml
* :robot: Configured reference (ref_) environment to have quota of 120000 requests per minute (other environments remain at 2400 per minute, with a per-app limit of 1200 per minute).
* :robot: Reordered parameters in APIGEE_ENVIRONMENTS in manifest_template to put the name first
* :robot: Modified release pipeline to deploy reference (ref) environment when internal-qa succeeds
* :robot: Disabled status monitoring for ref environment
=> NHSO-19114: Add reference environment

postman/NHS App - ref (Load Testing).postman_environment copy.json
=> NHSO-19204: Add ref environment to postman

azure/azure-release-pipeline.yml
=> NHSO-19114: Fix environment name typo

specification/nhs-app.yaml
=> NHSO-18713: Default notification content update

specification/components/schemas/Markdown.yaml
=> NHSO-0000: Fix indentation in markdown documentation

specification/components/schemas/requests/communication/communication-in-app-push-notifications.yaml, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/requests/communication/communication-push-notifications.yaml
=> NHSO 0001 fix broken link valid nhs number

specification/components/examples/responses/communication/400tooManyRecipients.json, specification/components/examples/responses/communication/report/200successEvents.json, specification/components/schemas/requests/communication/communication-in-app-push-notifications.yaml, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/requests/communication/communication-push-notifications.yaml, specification/components/schemas/responses/communication/communication-in-app-push-notifications.yaml, specification/components/schemas/responses/communication/communication-in-app.yaml, specification/components/schemas/responses/communication/communication-push-notifications.yaml, specification/components/schemas/responses/communication/report/events.yaml, specification/nhs-app.yaml
* NHSO-19578 - deprecation of in-app-with-notification endpoint
* NHSO-19711 - reducing the maximum number of recipients per request
=> NHSO-19578: NHSO-19711: Specification changes for two stories

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests.csproj
* Upgrade FluentAssertions package to 6.6.0
=> NHSO-18619: Upgrade Fluent Assertions to 6.6.0

specification/components/examples/responses/communication/report/200successEvents.json
* Documentation change - remove example "Cancelled" event from event report response.
=> NHSO-19578: Remove example Cancelled event

specification/components/schemas/requests/communication/communication-in-app-push-notifications.yaml, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/requests/communication/communication-push-notifications.yaml, specification/components/schemas/responses/communication/communication-in-app-push-notifications.yaml, specification/components/schemas/responses/communication/communication-in-app.yaml, specification/components/schemas/responses/communication/communication-push-notifications.yaml, specification/nhs-app.yaml
API specification changes in relation to two of these changes - NHSO-19711 and NHSO-19578
*  Send an in-app message
*  Send a push notification
*  Send an in-app and push notification
Only content & schema format changes
=> NHSO-19711: Documentation update recommended by content designer 

postman/NHS App.postman_collection.json
* Removal of in-app-with-notification endpoint from Postman collection
=> NHSO-19579: Postman changes - removal of in-app-with-notification

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs
* Removal of in-app-with-notification endpoint from integration tests
=> NHSO-19579: Integration test changes - removal of in-app-with-notification

specification/components/examples/responses/communication/report/200successEvents.json, specification/components/schemas/responses/communication/report/events.yaml
Removes NhsNumber from daily event endpoint documentation
* Removes NhsNumber from daily event endpoint documentation
=> NHSO-19992: Update docs to reflect removal of NhsNumber from daily event report

specification/components/examples/responses/communication/report/200successEvents.json, specification/components/schemas/responses/communication/report/events.yaml
* Remove Failed event status from API documentation.
=> NHSO-10940: API specification - Remove Failed event from event enum

specification/nhs-app.yaml
* Change of specification heading from "Authorisation" to "Security and authorisation"
=> Change Authorisation heading

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/FhirR4IdentifierSystem.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/TestConfiguration.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/test.runsettings
Integration test changes for requester field
* Added requester object for positive scenarios 
* Added new negative test case for invalid identifier
=> NHSO-20647: Proxy layer integration test changes for requester

specification/components/examples/requests/communication/in-app.json, specification/components/examples/responses/communication/201successInApp.json, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/responses/communication/communication-in-app.yaml
* Remove requester.display from schema and examples.
=> NHSO-20629: Remove requester.display

manifest_template.yml
* :robot: Increase quota and spike arrest policies in production environment only to 12000 requests per minute per application, and 60000 requests per minute overall.
=> NHSO-20789: Increase rate limits

specification/nhs-app.yaml
* There are only two Communication endpoints following the removal of the in-app-with-notification endpoint.
=> NHSO-19579: Documentation correction

specification/nhs-app.yaml
=> Nhso 0001 amp 257 correct uk core version number

specification/nhs-app.yaml
* Draw attention to location of markdown details for in-app messages
=> NHSO-20912: draw attention to location of markdown details

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/FhirR4IdentifierSystem.cs
* Communication ID identifier system change
=> NHSO-22094: Communication ID identifier system change

specification/nhs-app.yaml
* Document the current rate limits
=> NHSO-22250: Document rate limits

specification/components/examples/responses/communication/201successInApp.json, specification/components/examples/responses/communication/201successNotification.json, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/requests/communication/communication-push-notifications.yaml, specification/components/schemas/responses/communication/communication-in-app.yaml, specification/components/schemas/responses/communication/communication-push-notifications.yaml, specification/components/schemas/responses/communication/report/events.yaml
* Specification change - Communication ID identifier system change
=> NHSO-22094: Communication ID identifier system change - documentation

specification/components/examples/responses/communication/report/200successEventsFhir.json, specification/components/schemas/responses/communication/report/events-fhir.yaml, specification/nhs-app.yaml
API specification for new version of Event Report endpoint, and realtime receipts.
=> NHSO-20659: Event Report and Realtime Receipt documentation

specification/nhs-app.yaml
=> NHSO-20569: Add missing full stop.

specification/nhs-app.yaml
* Disalbe 'try this API' in specification, as API does not currently have a sandbox.
=> NHSO-0000: Disable 'try this API' in specification

postman/NHS App.postman_collection.json
* Postman updates for forthcoming receipt and replies reports
=> NHSO-21907: Postman updates for receipt and replies reports

specification/components/examples/responses/communication/403permissionsMissingForEventsReport.json, specification/components/examples/responses/communication/403permissionsMissingForReceiptsReport.json, specification/nhs-app.yaml
=> NHSO-21907: Report permission messages

postman/NHS App.postman_collection.json, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationHttpFunctionsFhirR4Tests.cs, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/FhirR4IdentifierSystem.cs
* Integration and postman collection related changes for keyword reply
=> NHSO-21988: Keyword reply integration test changes

specification/components/examples/requests/communication/in-app-with-keyword-reply.json, specification/components/examples/responses/communication/201successInAppWithKeywordReply.json, specification/components/examples/responses/communication/400invalidContainedAnswerOptionLength.json, specification/components/examples/responses/communication/400invalidContainedItemType.json, specification/components/examples/responses/communication/400invalidContainedResourceType.json, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/responses/communication/communication-in-app.yaml, specification/nhs-app.yaml
* Keyword reply documentation changes
=> NHSO-21988: Keyword reply documentation changes

specification/nhs-app.yaml
=> NHSO-24008: s/swg/svg/

tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/CommunicationEndpointsTests.cs
* FTR Integration Tests Changes
=> NHSO-24013: FTR Integration tests

postman/NHS App.postman_collection.json, specification/components/examples/requests/communication/in-app-with-free-text-reply.json, specification/components/examples/responses/communication/201successInAppWithFreeTextReply.json, specification/components/examples/responses/communication/400invalidContainedItemType.json, specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/responses/communication/communication-in-app.yaml, specification/nhs-app.yaml
=> NHSO-24013: FTR API Specification Changes

README.md, package.json
Reverting openapi-generator to speccy in order to cope with external $refs.
=> NHSO-0000: Revert to Speccy so references are resolved.

specification/nhs-app.yaml
=> NHSO-28038: Remove wording on public facing supplier documentation

specification/components/schemas/requests/communication/communication-in-app.yaml, specification/components/schemas/requests/communication/communication-push-notifications.yaml
=> NHSO-30164: Add 'OnBehalfOf' field.

package-lock.json, package.json
=> NHSO-0000: Clean up packages.

pyproject.toml, specification/nhs-app.yaml
=> NHSO-34608: Real Time Receipts document updates

.github/workflows/continuous-integration.yml
=> NHSO-0000: Upgrade node.

specifications-callbacks/realtime-receipts/components/examples/requests/task/notificationattempted.json, specifications-callbacks/realtime-receipts/realtime-receipt.yaml
=> NHSO-0000: Add NotificationAttempted to the schema.

azure/templates/run-integration-tests.yml, tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests/Nhs.App.Api.Integration.Tests.csproj, tests/Nhs.App.Api.Integration.Tests/global.json
=> NHSO-48379: Upgrade to .NET 8.

manifest_template.yml
Bumps the quota to 24,000 requests per minute (400 TPS) before throttling.
=> NHSO-51705: Bump to 400 TPS.

.github/workflows/continuous-integration.yml
=> NHSO-0000: Update actions/cache task to v3.

postman/NHS App - dev (NHS Login sandpit).postman_environment.json, postman/NHS App.postman_collection.json, specification/nhs-app.yaml
=> NHSO-61032: Dep documentaion and postman collection changes
